apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-app
  ports:
    - port: 80
      nodePort: 30082 # exposing to local, to access this service
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paypal-app
  template:
    metadata:
      labels:
        app: paypal-app
    spec:
      containers:
        - name: paypal-app
          image: proj2_paypal-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: paypal_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: paypal_dbName
          imagePullPolicy: Never