apiVersion: v1
kind: Service
metadata:
  name: credit-service
spec:
  selector:
    app: credit-app
  ports:
    - port: 80
      nodePort: 30082 # exposing to local, to access this service
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-app
  template:
    metadata:
      labels:
        app: account-app
    spec:
      containers:
        - name: credit-app
          image: proj2_credit-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: credit_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: credit_dbName
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret-key
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
          imagePullPolicy: Never