version: '3.9'

services:

# 8080, for now reserved for main api gateway

# 8081-8089 fir services
  product-service:
    ports:
      - 8081:8081
    restart: always
    build:
      context: ./product-service
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: swa2-mysql
    depends_on:
      swa2-mysql:
        condition: service_healthy

  account-service:
    ports:
      - 8082:8082
    restart: always
    build:
      context: ./account-service
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: swa2-mysql
    depends_on:
      swa2-mysql:
        condition: service_healthy

  order-service:
    ports:
      - 8083:8083
    restart: always
    build:
      context: ./account-service
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: swa2-mysql
    depends_on:
      swa2-mysql:
        condition: service_healthy

  shipping-service:
    ports:
      - 8084:8084
    restart: always
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: swa2-mysql
    depends_on:
      swa2-mysql:
        condition: service_healthy

# 8090 (for payment gateway) 8091, 8092, 8093 for payment services
#  creditcard-service:
#    ports:
#      - 8091:8091
#    restart: always
#    build:
#      context: ./payment/creditcard-service
#      dockerfile: Dockerfile
#    environment:
#      MYSQL_URL: swa2-mysql
#    depends_on:
#      swa2-mysql:
#        condition: service_healthy

# Auth Service
  auth-service:
    ports:
      - 8070:8070
    restart: always
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: swa2-mysql
    depends_on:
      swa2-mysql:
        condition: service_healthy

# MYSQL Database, with multiple schemas for all services
  swa2-mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: user
#      MYSQL_PASSWORD: user
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 100s
      retries: 3
    restart: on-failure
    volumes:
      - swa2_mysql:/var/lib/mysql
      - ./zmysql/init:/docker-entrypoint-initdb.d

volumes:
  swa2_mysql:
