apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
data:
  spring.datasource.url: "jdbc:mysql://${MYSQL_URL:localhost}:3306/account-db?createDatabaseIfNotExist=true"

  spring.jpa.hibernate.ddl-auto: "update"
---
apiVersion: v1
kind: Secret
metadata:
  name: account-service-secret
type: Opaque
stringData:
  spring.datasource.username: "root"
  spring.datasource.password: "root"