spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
      discovery:
        all-namespaces: true
#      loadbalancer:
#        mode: SERVICE

    discovery:
      enabled: true

eureka:
  client:
    enabled: false

