eureka:
  client:
    enabled: false

spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
      loadbalancer:
        mode: SERVICE

    discovery:
      enabled: true