apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-app
  ports:
    - port: 80
      nodePort: 30082 # exposing to local, to access this service
      targetPort: 8082
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-app
  template:
    metadata:
      labels:
        app: account-app
    spec:
      containers:
        - name: account-app
          image: proj2_account-service
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: account_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: account_dbName
          imagePullPolicy: Never