apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      nodePort: 30083 # exposing to local, to access this service
      targetPort: 8083
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: proj2_order-service
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: order_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: order_dbName
          imagePullPolicy: Never