apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping-app
  ports:
    - port: 80
      nodePort: 30088 # exposing to local, to access this service
      targetPort: 8088
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-app
  template:
    metadata:
      labels:
        app: shipping-app
    spec:
      containers:
        - name: shipping-app
          image: proj2_shipping-service
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: shipping_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: shipping_dbName
          imagePullPolicy: Never