apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  selector:
    app: stock-app
  ports:
    - port: 80
      nodePort: 30087 # exposing to local, to access this service
      targetPort: 8087
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-app
  template:
    metadata:
      labels:
        app: stock-app
    spec:
      containers:
        - name: stock-app
          image: proj2_stock-service
#          readinessProbe:
#            httpGet:
#              port: 80
#              path: /actuator/health/readiness
#          livenessProbe:
#            httpGet:
#              port: 80
#              path: /actuator/health/liveness
#          lifecycle:
#            preStop:
#              exec:
#                command:
#                  - sh
#                  - '-c'
#                  - sleep 10
          ports:
            - containerPort: 8087
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: stock_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: stock_dbName
          imagePullPolicy: Never